ALTER TABLE products
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE sales
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE purchases
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
